# -*- coding: utf-8 -*-
"""creating embeddings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNZtJmHmgcvZFdEuYYJE-rwCLZ3WK3HG
"""

database = pd.read_csv("/content/drive/MyDrive/Komal varma/medicinedataset.csv")

database.head()

!pip install huggingface
!pip install sentence-transformers
!pip install torch

import pandas as pd

import torch
from sentence_transformers import SentenceTransformer
import pickle

# Loading model
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

df = pd.read_csv("/content/drive/MyDrive/Komal varma/medicinedataset.csv")

df.head()

# Creating embeddings
embeddings = model.encode(df['medicine'], show_progress_bar=True)

# Saving the embeddings
with open('../data/medicine-embeddings.pkl', "wb") as fOut:
    pickle.dump(embeddings, fOut)

# Loading the embeddings
with open('../data/medicine-embeddings.pkl', "rb") as fIn:
    embeddings = pickle.load(fIn)

print(f"Shape of one embedding{embeddings[0].shape}")

# Perform Semantic Search for substitutes
def find_substitutes(prompt, df, model, embeddings, top_k=5):
    # Get embedding for the prompt
    prompt_embedding = model.encode(prompt, convert_to_tensor=True)

    # Perform semantic search
    hits = util.semantic_search(prompt_embedding, embeddings, top_k=top_k)

    # Extract substitute medicines
    substitute_indices = hits[0]['corpus_id']
    substitutes = df.iloc[substitute_indices]['substitutes'].tolist()

    return substitutes

# Example Prompt
prompt = "azithral 500 tablet"

# Find substitutes
substitutes = find_substitutes(prompt, df, model, embeddings, top_k=5)
print(substitutes)

